name: .NET CI/CD with Code Coverage

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore TrabajoTarjeta2025/TrabajoTarjeta2025.sln

    - name: Build
      run: dotnet build TrabajoTarjeta2025/TrabajoTarjeta2025.sln --no-restore --configuration Release

    - name: Run tests with coverage
      run: dotnet test TrabajoTarjeta2025.test/testTrabajoTarjeta2025.csproj --no-build --configuration Release --collect:"XPlat Code Coverage"

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
